export const REGION_KOREAN = {
    JAPAN: '일본',
    CHINA: '중국',
    SOUTHEAST_ASIA: '동남아',
    AMERICAS: '미주',
    EUROPE: '유럽',
    SOUTH_PACIFIC: '남태평양', // 괌/사이판 포함
    OTHERS: '기타'
};

const CITY_REGION_MAP: Record<string, string> = {
    // 일본
    '도쿄': REGION_KOREAN.JAPAN, '나리타': REGION_KOREAN.JAPAN, '하네다': REGION_KOREAN.JAPAN,
    '오사카': REGION_KOREAN.JAPAN, '간사이': REGION_KOREAN.JAPAN,
    '후쿠오카': REGION_KOREAN.JAPAN,
    '삿포로': REGION_KOREAN.JAPAN, '치토세': REGION_KOREAN.JAPAN,
    '오키나와': REGION_KOREAN.JAPAN, '나하': REGION_KOREAN.JAPAN,
    '나고야': REGION_KOREAN.JAPAN,
    '마츠야마': REGION_KOREAN.JAPAN, '다카마쓰': REGION_KOREAN.JAPAN, '요나고': REGION_KOREAN.JAPAN,
    '나가사키': REGION_KOREAN.JAPAN, '히로시마': REGION_KOREAN.JAPAN,
    '구마모토': REGION_KOREAN.JAPAN, '가고시마': REGION_KOREAN.JAPAN,

    // 중국/홍콩/대만
    '베이징': REGION_KOREAN.CHINA, '상하이': REGION_KOREAN.CHINA, '상해': REGION_KOREAN.CHINA,
    '칭다오': REGION_KOREAN.CHINA, '청도': REGION_KOREAN.CHINA,
    '광저우': REGION_KOREAN.CHINA, '장가계': REGION_KOREAN.CHINA,
    '홍콩': REGION_KOREAN.CHINA, '마카오': REGION_KOREAN.CHINA,
    '대만': REGION_KOREAN.CHINA, '타이페이': REGION_KOREAN.CHINA, '가오슝': REGION_KOREAN.CHINA,

    // 동남아
    '방콕': REGION_KOREAN.SOUTHEAST_ASIA, '돈무앙': REGION_KOREAN.SOUTHEAST_ASIA, '수완나품': REGION_KOREAN.SOUTHEAST_ASIA,
    '다낭': REGION_KOREAN.SOUTHEAST_ASIA, '나트랑': REGION_KOREAN.SOUTHEAST_ASIA, '깜랑': REGION_KOREAN.SOUTHEAST_ASIA,
    '하노이': REGION_KOREAN.SOUTHEAST_ASIA, '호치민': REGION_KOREAN.SOUTHEAST_ASIA, '푸꾸옥': REGION_KOREAN.SOUTHEAST_ASIA,
    '세부': REGION_KOREAN.SOUTHEAST_ASIA, '보홀': REGION_KOREAN.SOUTHEAST_ASIA, '마닐라': REGION_KOREAN.SOUTHEAST_ASIA, '클락': REGION_KOREAN.SOUTHEAST_ASIA, '보라카이': REGION_KOREAN.SOUTHEAST_ASIA, '칼리보': REGION_KOREAN.SOUTHEAST_ASIA,
    '싱가포르': REGION_KOREAN.SOUTHEAST_ASIA, '싱가폴': REGION_KOREAN.SOUTHEAST_ASIA,
    '코타키나발루': REGION_KOREAN.SOUTHEAST_ASIA, '발리': REGION_KOREAN.SOUTHEAST_ASIA, '덴파사': REGION_KOREAN.SOUTHEAST_ASIA,
    '치앙마이': REGION_KOREAN.SOUTHEAST_ASIA, '푸켓': REGION_KOREAN.SOUTHEAST_ASIA,
    '바탐': REGION_KOREAN.SOUTHEAST_ASIA, '마나도': REGION_KOREAN.SOUTHEAST_ASIA,
    '비엔티안': REGION_KOREAN.SOUTHEAST_ASIA, '라오스': REGION_KOREAN.SOUTHEAST_ASIA,

    // 미주 (하와이 포함)
    'LA': REGION_KOREAN.AMERICAS, '로스앤젤레스': REGION_KOREAN.AMERICAS,
    '뉴욕': REGION_KOREAN.AMERICAS, '샌프란시스코': REGION_KOREAN.AMERICAS,
    '시애틀': REGION_KOREAN.AMERICAS, '라스베가스': REGION_KOREAN.AMERICAS,
    '밴쿠버': REGION_KOREAN.AMERICAS, '토론토': REGION_KOREAN.AMERICAS,
    '하와이': REGION_KOREAN.AMERICAS, '호놀룰루': REGION_KOREAN.AMERICAS,

    // 유럽
    '파리': REGION_KOREAN.EUROPE, '런던': REGION_KOREAN.EUROPE, '로마': REGION_KOREAN.EUROPE,
    '프랑크푸르트': REGION_KOREAN.EUROPE, '바르셀로나': REGION_KOREAN.EUROPE, '마드리드': REGION_KOREAN.EUROPE,
    '프라하': REGION_KOREAN.EUROPE, '비엔나': REGION_KOREAN.EUROPE, '취리히': REGION_KOREAN.EUROPE,
    '암스테르담': REGION_KOREAN.EUROPE, '이스탄불': REGION_KOREAN.EUROPE,

    // 남태평양 (괌/사이판 포함)
    '괌': REGION_KOREAN.SOUTH_PACIFIC,
    '사이판': REGION_KOREAN.SOUTH_PACIFIC,
    '시드니': REGION_KOREAN.SOUTH_PACIFIC, '브리즈번': REGION_KOREAN.SOUTH_PACIFIC, '멜버른': REGION_KOREAN.SOUTH_PACIFIC,
    '오클랜드': REGION_KOREAN.SOUTH_PACIFIC
};

export function getRegionByCity(city: string): string {
    if (!city) return REGION_KOREAN.OTHERS;

    // 정확한 매칭
    if (CITY_REGION_MAP[city]) {
        return CITY_REGION_MAP[city];
    }

    // 부분 매칭 (예: "도쿄(나리타)" -> "도쿄"로 매칭)
    for (const [key, region] of Object.entries(CITY_REGION_MAP)) {
        if (city.includes(key)) {
            return region;
        }
    }

    return REGION_KOREAN.OTHERS;
}
