export const REGION_KOREAN = {
    JAPAN: '일본',
    CHINA: '중국',
    SOUTHEAST_ASIA: '동남아',
    AMERICAS: '미주',
    EUROPE: '유럽',
    SOUTH_PACIFIC: '남태평양', // 괌/사이판 포함
    OTHERS: '기타'
};

const CITY_REGION_MAP: Record<string, string> = {
    // 일본
    '도쿄': REGION_KOREAN.JAPAN, '나리타': REGION_KOREAN.JAPAN, '하네다': REGION_KOREAN.JAPAN,
    '오사카': REGION_KOREAN.JAPAN, '간사이': REGION_KOREAN.JAPAN,
    '후쿠오카': REGION_KOREAN.JAPAN,
    '삿포로': REGION_KOREAN.JAPAN, '치토세': REGION_KOREAN.JAPAN, '북해도': REGION_KOREAN.JAPAN, '홋카이도': REGION_KOREAN.JAPAN,
    '오키나와': REGION_KOREAN.JAPAN, '나하': REGION_KOREAN.JAPAN,
    '나고야': REGION_KOREAN.JAPAN,
    '마츠야마': REGION_KOREAN.JAPAN, '다카마쓰': REGION_KOREAN.JAPAN, '다카마츠': REGION_KOREAN.JAPAN, '요나고': REGION_KOREAN.JAPAN,
    '나가사키': REGION_KOREAN.JAPAN, '히로시마': REGION_KOREAN.JAPAN,
    '구마모토': REGION_KOREAN.JAPAN, '가고시마': REGION_KOREAN.JAPAN,
    '오이타': REGION_KOREAN.JAPAN, '시즈오카': REGION_KOREAN.JAPAN,
    '기타큐슈': REGION_KOREAN.JAPAN, '사가': REGION_KOREAN.JAPAN, '고베': REGION_KOREAN.JAPAN,
    '시모지시마': REGION_KOREAN.JAPAN, '미야코지마': REGION_KOREAN.JAPAN,
    '미야자키': REGION_KOREAN.JAPAN, '니가타': REGION_KOREAN.JAPAN, '오카야마': REGION_KOREAN.JAPAN,
    '후쿠에': REGION_KOREAN.JAPAN, '쿠마모토': REGION_KOREAN.JAPAN, '도야마': REGION_KOREAN.JAPAN,
    '이바라키': REGION_KOREAN.JAPAN, '아키타': REGION_KOREAN.JAPAN, '고치': REGION_KOREAN.JAPAN,
    '이즈모': REGION_KOREAN.JAPAN, '우베': REGION_KOREAN.JAPAN, '오비히로': REGION_KOREAN.JAPAN,
    '아사히카와': REGION_KOREAN.JAPAN, '쓰시마': REGION_KOREAN.JAPAN, '대마도': REGION_KOREAN.JAPAN,

    // 중국/홍콩/대만
    '베이징': REGION_KOREAN.CHINA, '상하이': REGION_KOREAN.CHINA, '상해': REGION_KOREAN.CHINA,
    '칭다오': REGION_KOREAN.CHINA, '청도': REGION_KOREAN.CHINA,
    '광저우': REGION_KOREAN.CHINA, '장가계': REGION_KOREAN.CHINA,
    '홍콩': REGION_KOREAN.CHINA, '마카오': REGION_KOREAN.CHINA,
    '대만': REGION_KOREAN.CHINA, '타이페이': REGION_KOREAN.CHINA, '타이베이': REGION_KOREAN.CHINA, '가오슝': REGION_KOREAN.CHINA, '타이중': REGION_KOREAN.CHINA, '송산': REGION_KOREAN.CHINA, '화련': REGION_KOREAN.CHINA,
    '산야': REGION_KOREAN.CHINA, '싼야': REGION_KOREAN.CHINA, '삼아': REGION_KOREAN.CHINA,
    '위해': REGION_KOREAN.CHINA, '웨이하이': REGION_KOREAN.CHINA,
    '연길': REGION_KOREAN.CHINA, '옌지': REGION_KOREAN.CHINA,
    '하문': REGION_KOREAN.CHINA, '샤먼': REGION_KOREAN.CHINA,
    '연태': REGION_KOREAN.CHINA, '옌타이': REGION_KOREAN.CHINA,
    '제남': REGION_KOREAN.CHINA, '지난': REGION_KOREAN.CHINA,
    '하얼빈': REGION_KOREAN.CHINA, '대련': REGION_KOREAN.CHINA, '다롄': REGION_KOREAN.CHINA,
    '구이린': REGION_KOREAN.CHINA, '계림': REGION_KOREAN.CHINA,
    '화리엔': REGION_KOREAN.CHINA, '하나마키': REGION_KOREAN.JAPAN,
    '시안': REGION_KOREAN.CHINA, '서안': REGION_KOREAN.CHINA,
    '창사': REGION_KOREAN.CHINA, '장사': REGION_KOREAN.CHINA,
    '청두': REGION_KOREAN.CHINA, '충칭': REGION_KOREAN.CHINA, '쿤밍': REGION_KOREAN.CHINA,
    '선양': REGION_KOREAN.CHINA, '선전': REGION_KOREAN.CHINA, '톈진': REGION_KOREAN.CHINA,
    '난창': REGION_KOREAN.CHINA, '리장': REGION_KOREAN.CHINA, '시닝': REGION_KOREAN.CHINA,
    '둔황': REGION_KOREAN.CHINA, '인촨': REGION_KOREAN.CHINA, '타이위안': REGION_KOREAN.CHINA,
    '자위관': REGION_KOREAN.CHINA, '자이위관': REGION_KOREAN.CHINA,
    '친황다오': REGION_KOREAN.CHINA, '잔장': REGION_KOREAN.CHINA, '후허하오터': REGION_KOREAN.CHINA,
    '장자제': REGION_KOREAN.CHINA, '오르도스': REGION_KOREAN.CHINA, '우한': REGION_KOREAN.CHINA,
    '정저우': REGION_KOREAN.CHINA, '창춘': REGION_KOREAN.CHINA, '무단장': REGION_KOREAN.CHINA,
    '하이커우': REGION_KOREAN.CHINA, '구이양': REGION_KOREAN.CHINA,
    '난징': REGION_KOREAN.CHINA, '항저우': REGION_KOREAN.CHINA,

    // 동남아
    '방콕': REGION_KOREAN.SOUTHEAST_ASIA, '돈무앙': REGION_KOREAN.SOUTHEAST_ASIA, '수완나품': REGION_KOREAN.SOUTHEAST_ASIA,
    '다낭': REGION_KOREAN.SOUTHEAST_ASIA, '나트랑': REGION_KOREAN.SOUTHEAST_ASIA, '깜랑': REGION_KOREAN.SOUTHEAST_ASIA,
    '하노이': REGION_KOREAN.SOUTHEAST_ASIA, '호치민': REGION_KOREAN.SOUTHEAST_ASIA, '푸꾸옥': REGION_KOREAN.SOUTHEAST_ASIA,
    '세부': REGION_KOREAN.SOUTHEAST_ASIA, '보홀': REGION_KOREAN.SOUTHEAST_ASIA, '마닐라': REGION_KOREAN.SOUTHEAST_ASIA, '클락': REGION_KOREAN.SOUTHEAST_ASIA, '보라카이': REGION_KOREAN.SOUTHEAST_ASIA, '칼리보': REGION_KOREAN.SOUTHEAST_ASIA,
    '싱가포르': REGION_KOREAN.SOUTHEAST_ASIA, '싱가폴': REGION_KOREAN.SOUTHEAST_ASIA,
    '코타키나발루': REGION_KOREAN.SOUTHEAST_ASIA, '발리': REGION_KOREAN.SOUTHEAST_ASIA, '덴파사': REGION_KOREAN.SOUTHEAST_ASIA,
    '치앙마이': REGION_KOREAN.SOUTHEAST_ASIA, '푸켓': REGION_KOREAN.SOUTHEAST_ASIA, '푸껫': REGION_KOREAN.SOUTHEAST_ASIA,
    '바탐': REGION_KOREAN.SOUTHEAST_ASIA, '마나도': REGION_KOREAN.SOUTHEAST_ASIA,
    '비엔티안': REGION_KOREAN.SOUTHEAST_ASIA, '비엔티엔': REGION_KOREAN.SOUTHEAST_ASIA, '라오스': REGION_KOREAN.SOUTHEAST_ASIA,
    '쿠알라룸푸르': REGION_KOREAN.SOUTHEAST_ASIA, '자카르타': REGION_KOREAN.SOUTHEAST_ASIA,
    '하이퐁': REGION_KOREAN.SOUTHEAST_ASIA, '양곤': REGION_KOREAN.SOUTHEAST_ASIA,
    '프놈펜': REGION_KOREAN.SOUTHEAST_ASIA, '씨엠립': REGION_KOREAN.SOUTHEAST_ASIA,
    '반다르세리베가완': REGION_KOREAN.SOUTHEAST_ASIA, '브루나이': REGION_KOREAN.SOUTHEAST_ASIA,

    // 미주 (하와이 포함)
    'LA': REGION_KOREAN.AMERICAS, '로스앤젤레스': REGION_KOREAN.AMERICAS,
    '뉴욕': REGION_KOREAN.AMERICAS, '샌프란시스코': REGION_KOREAN.AMERICAS,
    '시애틀': REGION_KOREAN.AMERICAS, '라스베가스': REGION_KOREAN.AMERICAS,
    '밴쿠버': REGION_KOREAN.AMERICAS, '토론토': REGION_KOREAN.AMERICAS,
    '하와이': REGION_KOREAN.AMERICAS, '호놀룰루': REGION_KOREAN.AMERICAS,

    // 유럽/중동/아프리카
    '파리': REGION_KOREAN.EUROPE, '런던': REGION_KOREAN.EUROPE, '로마': REGION_KOREAN.EUROPE,
    '프랑크푸르트': REGION_KOREAN.EUROPE, '바르셀로나': REGION_KOREAN.EUROPE, '마드리드': REGION_KOREAN.EUROPE,
    '프라하': REGION_KOREAN.EUROPE, '비엔나': REGION_KOREAN.EUROPE, '취리히': REGION_KOREAN.EUROPE,
    '암스테르담': REGION_KOREAN.EUROPE, '이스탄불': REGION_KOREAN.EUROPE,
    '이즈미르': REGION_KOREAN.EUROPE, '헬싱키': REGION_KOREAN.EUROPE,
    '트라브존': REGION_KOREAN.EUROPE, '마르세유': REGION_KOREAN.EUROPE,

    // 일본 (누락분 추가)
    '센다이': REGION_KOREAN.JAPAN, '하코다테': REGION_KOREAN.JAPAN, '도쿠시마': REGION_KOREAN.JAPAN,
    '구시로': REGION_KOREAN.JAPAN, '몬베츠': REGION_KOREAN.JAPAN, '이시가키': REGION_KOREAN.JAPAN,
    '아오모리': REGION_KOREAN.JAPAN, '고마쓰': REGION_KOREAN.JAPAN,

    // 남아시아/중앙아시아 → 기타
    '콜카타': REGION_KOREAN.OTHERS, '카트만두': REGION_KOREAN.OTHERS,
    '콜롬보': REGION_KOREAN.OTHERS, '비슈케크': REGION_KOREAN.OTHERS,
    '라호르': REGION_KOREAN.OTHERS, '파트나': REGION_KOREAN.OTHERS,
    '푸네': REGION_KOREAN.OTHERS, '스리나가르': REGION_KOREAN.OTHERS,
    '바라나시': REGION_KOREAN.OTHERS, '델리': REGION_KOREAN.OTHERS,
    '뭄바이': REGION_KOREAN.OTHERS, '몰디브': REGION_KOREAN.OTHERS,
    '고아': REGION_KOREAN.OTHERS, '코치': REGION_KOREAN.OTHERS, '보팔': REGION_KOREAN.OTHERS,
    '부지': REGION_KOREAN.OTHERS, '이슬라마바드': REGION_KOREAN.OTHERS,
    '타슈켄트': REGION_KOREAN.OTHERS, '오랄': REGION_KOREAN.OTHERS, '알마티': REGION_KOREAN.OTHERS,
    '블라디보스토크': REGION_KOREAN.OTHERS, '아디스아바바': REGION_KOREAN.OTHERS,
    '울란바토르': REGION_KOREAN.OTHERS,
    '라싸': REGION_KOREAN.CHINA, '우루무치': REGION_KOREAN.CHINA,

    // 남태평양 (괌/사이판 포함)
    '괌': REGION_KOREAN.SOUTH_PACIFIC,
    '사이판': REGION_KOREAN.SOUTH_PACIFIC,
    '시드니': REGION_KOREAN.SOUTH_PACIFIC, '브리즈번': REGION_KOREAN.SOUTH_PACIFIC, '멜버른': REGION_KOREAN.SOUTH_PACIFIC,
    '오클랜드': REGION_KOREAN.SOUTH_PACIFIC
};

/**
 * 도시명으로 지역을 조회한다. 매핑에 없으면 null을 반환한다.
 * "매핑 결과가 기타"와 "매핑에 아예 없음"을 구분해야 하는 호출부에서 사용한다.
 */
export function lookupRegionByCity(city: string): string | null {
    if (!city) return null;

    // 정확한 매칭
    if (CITY_REGION_MAP[city]) {
        return CITY_REGION_MAP[city];
    }

    // 부분 매칭 (예: "도쿄(나리타)" -> "도쿄"로 매칭)
    for (const [key, region] of Object.entries(CITY_REGION_MAP)) {
        if (city.includes(key)) {
            return region;
        }
    }

    return null;
}

export function getRegionByCity(city: string): string {
    return lookupRegionByCity(city) ?? REGION_KOREAN.OTHERS;
}
