import type { Page, Request } from 'playwright';
import { IncompleteScrapeError } from './scrape-errors';
import { SourceResponseError, assertNoSourceAccessBlockText } from './source-response';
import { YbtourOverlayError } from './ybtour-interaction';

/** Observe only the POST generated by the UI action; never send an extra request. */
async function waitForAction(page: Page, pathname: string, fields: Record<string, string>, click: () => Promise<void>) {
    const started = new Set<Request>();
    const onRequest = (request: Request) => { started.add(request); };
    page.on('request', onRequest);
    const pending = page.waitForResponse(response => {
        const request = response.request();
        const url = new URL(response.url());
        const params = new URLSearchParams(request.postData() || '');
        return started.has(request) && request.method() === 'POST' && url.origin === 'https://fly.ybtour.co.kr'
            && url.pathname === pathname && Object.entries(fields).every(([key, value]) => params.get(key) === value);
    }, { timeout: 20_000 }).then(response => ({ response }), error => ({ error }));
    try {
        await click();
        const result = await pending;
        assertNoSourceAccessBlockText('노랑풍선 화면 전환', await page.locator('body').innerText(), page.url());
        if (!('response' in result)) throw new IncompleteScrapeError('노랑풍선 화면 요청 응답 대기 실패', [JSON.stringify(fields)]);
        const response = result.response;
        if (!response.ok()) throw new SourceResponseError('http-status', `노랑풍선 HTTP ${response.status()}`, response.status());
        let timer: ReturnType<typeof setTimeout> | undefined;
        try {
            const body = await Promise.race([response.text(), new Promise<never>((_, reject) => {
                timer = setTimeout(() => reject(new IncompleteScrapeError('노랑풍선 응답 본문 대기 실패', [pathname])), 20_000);
            })]);
            assertNoSourceAccessBlockText('노랑풍선 응답', body, response.url());
        } finally { if (timer) clearTimeout(timer); }
    } finally { page.off('request', onRequest); }
}

async function waitRendered(page: Page, selector: string) {
    try {
        await page.waitForFunction(selector => {
            const visibleMask = Array.from(document.querySelectorAll('.dimBox.bg')).some(el =>
                el.getClientRects().length > 0 && getComputedStyle(el).visibility !== 'hidden');
            return !visibleMask && Boolean(document.querySelector(selector));
        }, selector, { timeout: 8000 });
    } catch {
        assertNoSourceAccessBlockText('노랑풍선 화면 갱신', await page.locator('body').innerText(), page.url());
        if (await page.locator('.dimBox.bg:visible').count()) throw new YbtourOverlayError('노랑풍선 응답 후 화면 덮개 미해제', [selector]);
        throw new IncompleteScrapeError('노랑풍선 응답 후 화면 갱신 실패', [selector]);
    }
}

export async function selectYbtourCity(page: Page, region: string, city: string, click: () => Promise<void>) {
    const oldTable = await page.$('#totalFareTable');
    try {
        await waitForAction(page, '/booking/findDiscountAir.lts', { svcTpCode: 'FARE', efcBannerCode: region, efcCityCode: city }, click);
        // The callback replaces div_farelist. Never retain handles to the previous city's table.
        if (oldTable) await page.waitForFunction(table => !table.isConnected, oldTable, { timeout: 8000 });
        await waitRendered(page, '#totalFareTable');
    } finally { await oldTable?.dispose(); }
}

export async function openYbtourFare(page: Page, onclick: string, click: () => Promise<void>) {
    const match = onclick.match(/listActive\(\s*(\d+)\s*,\s*['"]([^'"]+)['"]/);
    if (!match) throw new IncompleteScrapeError('노랑풍선 운임 조회 식별자 누락', [onclick]);
    await waitForAction(page, '/booking/findListDscInvSkdFare.lts', { loc: match[1], inhId: match[2] }, click);
    await waitRendered(page, `[id="cont_detail_${match[1]}"]:not(:empty)`);
}
