import type { Page, Request } from 'playwright';
import { IncompleteScrapeError } from './scrape-errors';
import { SourceResponseError, assertNoSourceAccessBlockText } from './source-response';
import { YbtourOverlayError, YbtourRecoverableActionError } from './ybtour-interaction';

// Fare searches can remain in flight beyond the normal UI transition deadline.
// Keep observing that same POST; never click again while its outcome is unknown.
export const YBTOUR_FARE_RESPONSE_TIMEOUT_MS = 120_000;

/** Observe only the POST generated by the UI action; never send an extra request. */
export async function waitForAction(page: Page, pathname: string, fields: Record<string, string>, click: () => Promise<void>, timeout = 40_000) {
    const started = new Set<Request>();
    const failed = new Map<Request, string>();
    const matches = (request: Request) => {
        const url = new URL(request.url());
        const params = new URLSearchParams(request.postData() || '');
        return request.method() === 'POST' && url.origin === 'https://fly.ybtour.co.kr'
            && url.pathname === pathname && Object.entries(fields).every(([key, value]) => params.get(key) === value);
    };
    const onRequest = (request: Request) => { if (matches(request)) started.add(request); };
    const onFailed = (request: Request) => {
        if (started.has(request)) failed.set(request, request.failure()?.errorText || 'request_failed');
    };
    page.on('request', onRequest);
    page.on('requestfailed', onFailed);
    const pending = page.waitForResponse(response => {
        return started.has(response.request());
    }, { timeout }).then(response => ({ response }), error => ({ error }));
    const slowTimer = setTimeout(() => console.warn(`[YB AJAX] slow response: ${JSON.stringify({ pathname, fields, requests: started.size, failed: failed.size })}`), timeout / 2);
    try {
        await click();
        const result = await pending;
        assertNoSourceAccessBlockText('노랑풍선 화면 전환', await page.locator('body').innerText(), page.url());
        if (!('response' in result)) {
            const state = started.size === 0 ? 'not_sent' : failed.size === started.size ? 'network_failed' : 'response_pending';
            const diagnostic = JSON.stringify({ pathname, fields, state, requests: started.size, errors: Array.from(failed.values()) });
            console.error(`[YB AJAX] ${diagnostic}`);
            // An outstanding request is ambiguous: do not replay it or reload the page.
            const ErrorType = state === 'response_pending' ? IncompleteScrapeError : YbtourRecoverableActionError;
            throw new ErrorType(`노랑풍선 화면 요청 응답 대기 실패 (${state})`, [diagnostic]);
        }
        const response = result.response;
        if (!response.ok()) throw new SourceResponseError('http-status', `노랑풍선 HTTP ${response.status()}`, response.status());
        let timer: ReturnType<typeof setTimeout> | undefined;
        try {
            const body = await Promise.race([response.text(), new Promise<never>((_, reject) => {
                timer = setTimeout(() => reject(new IncompleteScrapeError('노랑풍선 응답 본문 대기 실패', [pathname])), 20_000);
            })]);
            assertNoSourceAccessBlockText('노랑풍선 응답', body, response.url());
        } finally { if (timer) clearTimeout(timer); }
    } finally {
        clearTimeout(slowTimer);
        page.off('request', onRequest);
        page.off('requestfailed', onFailed);
    }
}

async function waitRendered(page: Page, selector: string) {
    try {
        await page.waitForFunction(selector => {
            const visibleMask = Array.from(document.querySelectorAll('.dimBox.bg')).some(el =>
                el.getClientRects().length > 0 && getComputedStyle(el).visibility !== 'hidden');
            return !visibleMask && Boolean(document.querySelector(selector));
        }, selector, { timeout: 8000 });
    } catch {
        assertNoSourceAccessBlockText('노랑풍선 화면 갱신', await page.locator('body').innerText(), page.url());
        if (await page.locator('.dimBox.bg:visible').count()) throw new YbtourOverlayError('노랑풍선 응답 후 화면 덮개 미해제', [selector]);
        throw new IncompleteScrapeError('노랑풍선 응답 후 화면 갱신 실패', [selector]);
    }
}

export async function selectYbtourCity(page: Page, region: string, city: string, click: () => Promise<void>) {
    const oldTable = await page.$('#totalFareTable');
    try {
        await waitForAction(page, '/booking/findDiscountAir.lts', { svcTpCode: 'FARE', efcBannerCode: region, efcCityCode: city }, click);
        // The callback replaces div_farelist. Never retain handles to the previous city's table.
        if (oldTable) await page.waitForFunction(table => !table.isConnected, oldTable, { timeout: 8000 });
        await waitRendered(page, '#totalFareTable');
    } finally { await oldTable?.dispose(); }
}

export async function openYbtourFare(page: Page, onclick: string, click: () => Promise<void>) {
    const match = onclick.match(/listActive\(\s*(\d+)\s*,\s*['"]([^'"]+)['"]/);
    if (!match) throw new IncompleteScrapeError('노랑풍선 운임 조회 식별자 누락', [onclick]);
    await waitForAction(page, '/booking/findListDscInvSkdFare.lts', { loc: match[1], inhId: match[2] }, click, YBTOUR_FARE_RESPONSE_TIMEOUT_MS);
    await waitRendered(page, `[id="cont_detail_${match[1]}"]:not(:empty)`);
}
