import assert from 'node:assert/strict';
import { classifyVisit, reusableVisit, parseVisitPayload, isPublicVisitPath, koreaVisitDay, VISIT_IDLE_MS } from '../src/lib/visit-analytics';

const a = '00000000-0000-4000-8000-000000000001';
const b = '00000000-0000-4000-8000-000000000002';
const now = Date.parse('2026-09-07T10:00:00+09:00');
const visit = {id:a,visitorId:b,startedAt:now-60_000,lastActivityAt:now-10_000,channel:'search'};
assert(reusableVisit(visit,b,now));
assert(!reusableVisit(visit,a,now));
assert(!reusableVisit({...visit,lastActivityAt:now - VISIT_IDLE_MS,startedAt:now - VISIT_IDLE_MS},b,now));
assert(!reusableVisit({...visit,lastActivityAt:now+1},b,now));
assert(!reusableVisit({...visit,channel:'google'},b,now));
const midnight = Date.parse('2026-09-08T00:00:00+09:00');
assert(!reusableVisit({...visit,startedAt:midnight-1000,lastActivityAt:midnight-1000},b,midnight));
assert.equal(koreaVisitDay(midnight),'2026-09-08');
const input = {visitId:a,visitorId:b,startedAt:now,channel:'search',action:'visit'};
assert.deepEqual(parseVisitPayload(input,now),input);
assert.equal(parseVisitPayload({...input,email:'must not persist'},now),null);
assert.equal(parseVisitPayload({...input,url:'https://example.test/?private=value'},now),null);
assert.equal(parseVisitPayload({...input,action:'session_start'},now),null);
assert.equal(parseVisitPayload({...input,startedAt:now+60_000},now),null);
assert(parseVisitPayload({...input,startedAt:midnight-1000},midnight+1000));
assert.equal(parseVisitPayload({...input,startedAt:midnight-1000},midnight+121_000),null);
assert.equal(classifyVisit('https://www.tikitikit.kr/?source=myrealtrip',''),'direct');
assert.equal(classifyVisit('https://www.tikitikit.kr/?source=ttang','https://m.search.naver.com/search.naver'),'search');
assert.equal(classifyVisit('https://www.tikitikit.kr/?utm_source=naver_blog&utm_medium=social',''),'social');
assert.equal(classifyVisit('https://www.tikitikit.kr/','https://m.blog.naver.com/post'),'social');
assert.equal(classifyVisit('https://www.tikitikit.kr/','https://google.com.evil.test/'),'referral');
assert.equal(classifyVisit('https://www.tikitikit.kr/','https://gemini.google.com/'),'ai');
assert.equal(classifyVisit('https://www.tikitikit.kr/?utm_source=chatgpt.com',''),'ai');
assert.equal(classifyVisit('https://www.tikitikit.kr/?utm_source=te31&utm_medium=community',''),'campaign');
assert.equal(classifyVisit('https://www.tikitikit.kr/','https://www.tikitikit.kr/flights/도쿄'),'unknown');
for (const path of ['/','/flights/도쿄','/drop/1','/tips/cheap-flights','/about']) assert(isPublicVisitPath(path));
for (const path of ['/admin','/preview/revisit','/api/flights','/privacy','/flights-secret']) assert(!isPublicVisitPath(path));
console.log('Visit contracts: 30 checks passed');
