import test from 'node:test';
import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import { currentSourceState, collectionDetail, type OnlineCollectionSchedule } from '../src/lib/admin-source-current';
import { buildSourceSlotBars, type SourceSlotEvent } from '../src/lib/admin-source-slots';
import { buildCollectionHistory, type CrawlHistoryEntry, type ActiveCollectionRun } from '../src/lib/admin-collection-history';
import AdminSourceCurrentNote from '../src/components/AdminSourceCurrentNote';
import { onlineCollectionInterval } from './online-collection-interval.mjs';
const now=Date.parse('2026-09-18T11:20:00Z'),at='2026-09-18T01:27:11.496Z';
const interval=onlineCollectionInterval({onlinePrimary:{lastAttemptAt:at}},new Date(now));
const schedule:OnlineCollectionSchedule={...interval,anchorAt:at,previousFailure:{at,detail:'remote_worker_identity_mismatch'}};
const online=(patch:Partial<Parameters<typeof currentSourceState>[0]>={})=>currentSourceState({source:'onlinetour',now,onlineSchedule:schedule,...patch});
test('actual failed attempt gets existing deterministic 3-day schedule, not ongoing failure',()=>{assert.equal(interval.intervalDays,3);assert.equal(online()?.kind,'rest');assert.equal(online()?.nextEligibleAt,'2026-09-21T01:27:11.496Z');assert.equal(online()?.previousFailure?.detail,'remote_worker_identity_mismatch');});
test('expiry removes rest even if previously returned API due=false',()=>assert.equal(online({now:Date.parse(schedule.nextCollectionAt!)}),null));
test('unknown, missing or future schedule never suppresses failure',()=>{for(const s of [undefined,{...schedule,anchorAt:'bad'},{...schedule,nextCollectionAt:null},{...schedule,anchorAt:'2026-09-22T00:00:00Z'},{...schedule,intervalDays:5}])assert.equal(online({onlineSchedule:s}),null);});
test('active collection and protection circuits override schedule rest',()=>{const active:ActiveCollectionRun={id:1,title:'test',event:'schedule',startedAt:at,updatedAt:at,url:'https://example.com',status:'in_progress',stage:'crawling',plannedSources:['onlinetour'],skippedSources:[]};assert.equal(online({active}),null);assert.equal(online({circuit:{nextProbeAt:'2026-09-19T00:00:00Z'}}),null);assert.equal(online({onlineSchedule:{...schedule,protectionUntil:'unknown'}}),null);});
const partial:CrawlHistoryEntry={timestamp:'2026-09-18T07:58:08Z',sites:{modetour:{total:76,partial:true,detail:'타오위안(TPE) HTTP 500 — 기존 1건 유지, 나머지 14구간 반영'}},alerts:[]};
const mode=(history:CrawlHistoryEntry[])=>currentSourceState({source:'modetour',now,history});
test('TPE 500 partial means unavailable, never confirmed sold out',()=>{const s=mode([partial]);assert.equal(s?.kind,'partial');assert.match(s!.message,/매물 유무 미확인/);assert.match(s!.message,/나머지는 반영/);assert.match(collectionDetail(partial.sites.modetour)!,/기존 1건 유지/);});
test('later success removes old partial warning',()=>assert.equal(mode([partial,{...partial,timestamp:'2026-09-18T08:00:00Z',sites:{modetour:{total:80,scraped:900}}}]),null));
test('later full failure is not masked as original partial',()=>assert.equal(mode([partial,{...partial,timestamp:'2026-09-18T08:00:00Z',sites:{modetour:{total:76,preserved:true,detail:'connection failed'}}}]),null));
test('unrelated and not-requested entries do not replace last real partial',()=>assert.equal(mode([partial,{...partial,timestamp:'2026-09-18T08:00:00Z',sites:{modetour:{total:76,skipped:true,skipReason:'not-requested'}}}])?.kind,'partial'));
test('ordinary empty success, other error and old unrelated source are not labeled TPE',()=>{const cases:CrawlHistoryEntry['sites'][]=[{modetour:{total:0}},{modetour:{total:2,partial:true,detail:'other API timeout'}},{onlinetour:{total:0}}];for(const sites of cases)assert.equal(mode([{...partial,sites}]),null);});
const failure:SourceSlotEvent={timestamp:at,value:0,preserved:true,skipped:false,manual:false,localFallback:false};
test('rest bars do not fabricate missing results or overwrite original failure',()=>{const bars=buildSourceSlotBars({source:'onlinetour',now,events:[failure],scheduledRest:online()!.rest,completedThrough:now});assert.equal(bars.find(b=>b.final===failure)?.status,'failed');assert.equal(bars.at(-1)?.status,'unscheduled');assert.equal(bars.at(-1)?.final,null);});
test('another source never inherits online rest',()=>assert.equal(buildSourceSlotBars({source:'ybtour',now,events:[],scheduledRest:online()!.rest,completedThrough:now}).at(-1)?.status,'missing'));
test('history stays immutable and retains failed execution',()=>{const h=[{...partial,sites:{onlinetour:{total:0,preserved:true,detail:'remote_worker_identity_mismatch'}}},partial];const before=JSON.stringify(h);assert.equal(buildCollectionHistory(h,[]).find(r=>r.sites.onlinetour)?.sites.onlinetour.preserved,true);mode(h);assert.equal(JSON.stringify(h),before);});
test('render separates current rest from expandable previous error',()=>{const html=renderToStaticMarkup(createElement(AdminSourceCurrentNote,{state:online()}));assert.match(html,/현재 회차는 조회하지 않습니다/);assert.match(html,/이후 정규 회차/);assert.match(html,/<details><summary>이전 실행 오류/);assert.match(html,/현재 회차의 실패를 뜻하지 않습니다/);assert.ok(!html.includes('remote_worker_identity_mismatch'));});
test('render partial explicitly says no inventory conclusion',()=>assert.match(renderToStaticMarkup(createElement(AdminSourceCurrentNote,{state:mode([partial])})),/매물 유무 미확인/));
