import assert from 'node:assert/strict';
import { parseShareDiscovery, loadShareDiscovery } from '../src/lib/server/share-discovery-report';
import { createShareFunnel, FUNNEL_EVENTS, shareFunnelContext } from '../src/lib/share-funnel';
import { connectVerifiedPostLinks } from '../src/lib/threads-post-links';
import { TE31_POSTS, matchTe31Campaign } from '../src/lib/te31-posts';
import type { Flight } from '../src/types/flight';
const url = 'https://www.tikitikit.kr/share-group/vietnam-260914?utm_source=te31&utm_medium=community&utm_campaign=tikitikit_te31_vietnam-260914&utm_content=share_group_vietnam-260914';
const threads = 'https://www.tikitikit.kr/share-group/sgn-260914?utm_source=threads&utm_medium=social&utm_campaign=tikitikit_threads&utm_content=share_m20136580';
const base: Flight = { id: 'modetour-ASIA-20136580', source: 'modetour', airline: 'air', departure: { city: '인천', airport: 'ICN', date: '2026-10-05', time: '10:00' }, arrival: { city: '호치민', airport: 'SGN', date: '2026-10-08', time: '10:00' }, price: 210000, currency: 'KRW', link: 'https://example.com' };
const outside = { ...base, id: 'outside', departure: { ...base.departure, date: '2026-10-10' } };
const inventory = [base, outside];
const memory = new Map<string, string>();
const storage = { getItem: (key: string) => memory.get(key) || null, setItem: (key: string, value: string) => { memory.set(key, value); } };
const events: string[] = [];
const emit = (event: string) => { events.push(event); };
assert.equal(createShareFunnel('https://www.tikitikit.kr/', storage, emit), null);
assert.equal(shareFunnelContext(url.replace('utm_source=te31','utm_source=google')), null);
let tracker = createShareFunnel(url, storage, emit, 1000)!;
tracker.view(); tracker.view(); tracker.detail(outside, inventory); tracker.booking(outside, inventory);
assert.deepEqual(events, [FUNNEL_EVENTS[0]]);
tracker.more(); tracker.more(); tracker.detail(base, inventory); tracker.detail({ ...base, id: 'same-schedule-agency' }, inventory);
assert.equal(events.length, 2);
tracker.detail(outside, inventory); tracker.booking(base, inventory); tracker.booking(outside, inventory); tracker.booking(outside, inventory);
assert.deepEqual(events, [...FUNNEL_EVENTS]);
tracker = createShareFunnel(url, storage, emit, 1100)!;
tracker.view(); tracker.more(); tracker.detail(outside, inventory); tracker.booking(outside, inventory);
assert.equal(events.length, 4, 'reload/back deduplicated');
createShareFunnel(threads, storage, emit, 1100)!.view(); assert.equal(events.length, 5, 'channels independent');
createShareFunnel(url, storage, emit, 1801001)!.view(); assert.equal(events.length, 6, 'expires');
const row = { dimensionValues: [{ value: FUNNEL_EVENTS[0] }, { value: url }], metricValues: [{ value: '2' }, { value: '3' }] };
const report = parseShareDiscovery({ rows: [row], rowCount: 1 });
assert.equal(report.rows[0].stages[0].users, 2);
assert.equal(report.rows[0].stages[1].count, 0);
assert.equal(parseShareDiscovery({ rows: [], rowCount: 0 }).hasData, false);
assert.equal(parseShareDiscovery({ rows: [row], rowCount: 5 }).available, false);
assert.equal(parseShareDiscovery({ rows: [row,row], rowCount: 2 }).available, false);
assert.equal(parseShareDiscovery({ rows: [row], metadata: { subjectToThresholding: true } }).available, false);
const mapped = connectVerifiedPostLinks([{ id: 'api-id', permalink: 'https://www.threads.com/@tikitikit.kr/post/DdQkTQYD99a', trackingContent: null, shareCode: null, trackingIssue: 'replies-unavailable' }])[0];
assert.equal(mapped.trackingContent, 'share_m20136580'); assert.equal(mapped.trackingIssue, 'replies-unavailable');
assert.equal(connectVerifiedPostLinks([{...mapped, trackingContent:null, trackingIssue:'multiple-links'}])[0].trackingContent,null);
assert.equal(TE31_POSTS.find(post => post.id === 5248)?.campaign, 'tikitikit_te31_vietnam-260914');
assert.equal(matchTe31Campaign('tikitikit_te31_vietnam-260914', [{name:'tikitikit_te31_vietnam-260914',source:'threads',users:4,sessions:4,detailOpenUsers:0,bookingClicks:0,bookingClickUsers:0}]), null);
async function main() {
    assert.equal((await loadShareDiscovery({} as never, 7, async () => { throw new Error('429'); })).available, false);
    console.log('PASS: tagged collection attribution, staged outside-group exploration, duplicate schedules, reload/back dedup, channel isolation, expiration, verified fallback and unavailable data');
}
main();
