import assert from 'node:assert/strict';
import { NextRequest } from 'next/server';
import { GET } from '../src/app/c/[code]/route';
import { GET as getThreadsLink } from '../src/app/t/[code]/route';
import { SHARE_GROUPS, resolveShareGroupFlights } from '../src/lib/share-groups';
import type { Flight } from '../src/types/flight';
async function main() {
    const guangzhou = SHARE_GROUPS['can-260918'];
    assert.equal(guangzhou.price, 99000);
    assert.deepEqual(guangzhou.flightIds, ['modetour-CHI-20081239', 'modetour-CHI-20081230']);
    const guangzhouFlights = guangzhou.flightIds.map(id => ({ id } as Flight));
    assert.deepEqual(resolveShareGroupFlights(guangzhou, [...guangzhouFlights, { id: 'unrelated' } as Flight]), guangzhouFlights);
    const threadsResponse = await getThreadsLink(new NextRequest('http://localhost/t/g-can-260918'), { params: Promise.resolve({ code: 'g-can-260918' }) });
    const threadsTarget = new URL(threadsResponse.headers.get('location')!);
    assert.equal(threadsTarget.pathname, '/share-group/can-260918');
    assert.equal(threadsTarget.searchParams.get('utm_source'), 'threads');
    assert.equal(threadsTarget.searchParams.get('utm_content'), 'share_group_can-260918');
    const china = SHARE_GROUPS['china-260918'];
    assert.deepEqual(china.routes?.map(route => route.flightIds.length), [1, 9, 2, 3]);
    assert.equal(new Set(china.flightIds).size, 15);
    assert.deepEqual(china.routes!.flatMap(route => route.flightIds), china.flightIds);
    const chinaFlights = china.flightIds.map(id => ({ id } as Flight));
    assert.deepEqual(resolveShareGroupFlights(china, [...chinaFlights, { id: 'unrelated' } as Flight]), chinaFlights);
    assert.deepEqual(resolveShareGroupFlights(china, chinaFlights.slice(1)), chinaFlights.slice(1));
    assert.deepEqual(resolveShareGroupFlights(china, []), []);
    const chinaResponse = await GET(new NextRequest('http://localhost/c/te31-china-260918'), { params: Promise.resolve({ code: 'te31-china-260918' }) });
    assert.equal(chinaResponse.status, 307);
    const chinaTarget = new URL(chinaResponse.headers.get('location')!);
    assert.equal(chinaTarget.pathname, '/share-group/china-260918');
    assert.deepEqual(Object.fromEntries(chinaTarget.searchParams), { utm_source: 'te31', utm_medium: 'community', utm_campaign: 'tikitikit_te31_china-260918', utm_content: 'share_group_china-260918' });
    const icnCode = 'icn-260909', icnGroup = SHARE_GROUPS[icnCode];
    const expectedIds = ['ttang-VJ0835ICNCXR-G110-2026-09-13', 'ttang-7C1501ICNCTS-G3-2026-09-18', 'modetour-ASIA-20135807'];
    assert.deepEqual(icnGroup.flightIds, expectedIds);
    assert.equal(icnGroup.routes?.length, 3);
    assert.deepEqual(icnGroup.routes!.flatMap(route => route.flightIds), expectedIds);
    const icnFlights = expectedIds.map(id => ({ id } as Flight));
    assert.deepEqual(resolveShareGroupFlights(icnGroup, [...icnFlights].reverse()), icnFlights);
    assert.deepEqual(resolveShareGroupFlights(icnGroup, [...icnFlights.slice(1), { id: 'other-flight' } as Flight]), icnFlights.slice(1));
    const icnResponse = await GET(new NextRequest(`http://localhost/c/te31-${icnCode}`), { params: Promise.resolve({ code: `te31-${icnCode}` }) });
    assert.equal(icnResponse.status, 307);
    const icnTarget = new URL(icnResponse.headers.get('location')!);
    assert.equal(icnTarget.pathname, `/share-group/${icnCode}`);
    assert.deepEqual(Object.fromEntries(icnTarget.searchParams), { utm_source: 'te31', utm_medium: 'community', utm_campaign: `tikitikit_te31_${icnCode}`, utm_content: `share_group_${icnCode}` });
    const code = 'pus-260908', group = SHARE_GROUPS[code];
    assert.equal(group.routes?.length, 5);
    assert.equal(group.flightIds.length,12);
    assert.deepEqual(group.routes!.flatMap(route => route.flightIds), group.flightIds);
    assert.equal(new Set(group.flightIds).size,12);
    const flights = group.flightIds.map(id => ({id} as Flight));
    assert.equal(resolveShareGroupFlights(group,flights).length,12);
    assert.equal(resolveShareGroupFlights(group,flights.slice(1)).length,11);
    assert.deepEqual(resolveShareGroupFlights(group,[]),[]);
    assert.ok(SHARE_GROUPS[code]);
    const response=await GET(new NextRequest(`http://localhost/c/te31-${code}`),{params:Promise.resolve({code:`te31-${code}`})});
    assert.equal(response.status,307);
    const target=new URL(response.headers.get('location')!);
    assert.equal(target.pathname,`/share-group/${code}`);
    assert.deepEqual(Object.fromEntries(target.searchParams),{utm_source:'te31',utm_medium:'community',utm_campaign:`tikitikit_te31_${code}`,utm_content:`share_group_${code}`});
    const legacy=await GET(new NextRequest('http://localhost/c/te31-pqc1438'),{params:Promise.resolve({code:'te31-pqc1438'})});
    assert.equal(new URL(legacy.headers.get('location')!).pathname,'/share-group/pqc1438');
    const invalid=await GET(new NextRequest('http://localhost/c/te31-unknown'),{params:Promise.resolve({code:'te31-unknown'})});
    assert.equal(invalid.status,302);
    console.log('Multi-route registration, exact ID expiry, UTM redirect and legacy links passed.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
