import assert from 'node:assert/strict';
import { buildInsights, splitRoute } from '../src/lib/price-watch-insights';
import { currentDropDestination } from '../src/lib/current-drop-destination';
import type { Flight } from '../src/types/flight';
const points = (price: number) => Array.from({length: 7}, (_,i) => ({date: `2026-09-${String(i+1).padStart(2,'0')}`,minPrice:price-i*1000,avgPrice:price,count:1}));
const history = { '인천-칼리보(보라카이)': points(250000), '인천-보라카이(깔리보)': points(300000), '서울(ICN)-보라카이(KLO)': points(280000), '서울-보라카이': points(100000), '김포-칼리보': points(350000) };
const original = JSON.stringify(history);
const result = buildInsights(history);
assert.equal(result.trackedRoutes,2);
assert.equal(result.rows.length,2);
assert.equal(result.rows.filter(r => r.departure === '인천').length,1);
assert.equal(JSON.stringify(history),original);
assert.equal(splitRoute('서울-보라카이'),null);
assert.equal(splitRoute('인천-보라카이'),null);
assert.equal(splitRoute('인천-칼리보(MPH)'),null);
assert.equal(splitRoute('서울(ICN)-보라카이(KLO)')?.key,splitRoute('인천-칼리보')?.key);
assert.notEqual(splitRoute('김포-칼리보')?.key,splitRoute('인천-칼리보')?.key);
const latestNoDrop = points(200000).map(p=>({...p,minPrice:200000}));
assert.equal(buildInsights({'인천-칼리보':latestNoDrop,'인천-보라카이(깔리보)':points(300000).slice(1)}).rows.length,0,'Do not pick a larger decline from a less complete duplicate');
const now=Date.parse('2026-09-15T03:00:00Z'); const f={id:'actual'} as Flight;
assert.equal(currentDropDestination({date:'2026-09-15',flightId:'actual'},[f],now),'/?flight=actual');
assert.equal(currentDropDestination({date:'2026-09-14',flightId:'actual'},[f],now),null);
assert.equal(currentDropDestination({date:'2026-09-15',flightId:'actual'},[],now),null);
assert.equal(currentDropDestination({date:'2026-09-15',flightId:'actual'},[f],Date.parse('2026-09-15T15:00:00Z')),null);
console.log('PASS: airport-aware aliases, intact historical series, no discount cherry-picking, current DROP/missing/expired/KST rollover');
